### ISSUE TITLE
[storefront-shelf-editor] Product number selector interaction

### ISSUE THREAD

**Issue by dfosco** [vtex-apps/storefront-theme#16]
- [x] Validate input — positive integers only
 - [x] Validate range — 2 - 6
 - [x] Reflect button click on field value
 - [ ] Disable *-* / *+* buttons when on the edge of the range

**Comment by dfosco** [comment]
`Disable - / + buttons when on the edge of the range` is still open!

**Comment by brenoc** [comment]
Ops

**Comment by dfosco** [comment]
@brenoc Can we close this one sometime soon? It's small stuff :package:

**Comment by brenoc** [comment]
sure, @dfosco. There's also an issue that when those buttons are clicked, they act like submitting the form

**Comment by dfosco** [comment]
@bellacorbo Bella, can you take a look at this and see if you could fix it? You're working on a similar thing with the SKU Selector.

Let me know if you need me to explain it a little better.

**Comment by dfosco** [comment]
@bellacorbo​oooooooo :sob:

**Comment by brenoc** [comment]
Moved to https://github.com/vtex-apps/storefront-shelf/issues/1
