### ISSUE TITLE
[prototype/category-page] Show/Hide interaction in filter list

### ISSUE THREAD

**Issue by dfosco** [vtex-apps/storefront-theme#34]
@amoreira @brenoc I was planning on showing/hiding the inner list of options with CSS, as seen in the two states below, but considering the list of categories can get _really_ huge, that wouldn't be really performant.

Ideally we would render the inner list only when the user clicks the button to open it — however that stops us from transitioning it using CSS animations. We could try using one of those packages for React animation, but I don't think it's worth it for the MVP.

Let's just roll with a dry "show/hide" interaction and improve later!

---

<img width="333" alt="e382116a-50e6-11e5-8fe5-445d5e1763c1" src="https://cloud.githubusercontent.com/assets/3229933/9619579/d9e71050-50e7-11e5-888c-9c568d255bff.png">

<img width="336" alt="screen shot 2015-09-01 at 8 22 12 pm" src="https://cloud.githubusercontent.com/assets/3229933/9619516/2f9a5b98-50e7-11e5-917f-6a9f62cf7df5.png">

**Comment by dfosco** [comment]
Closed by 8c174460802c0a8d9b03c5a7f002cfd20e963b0a

**Comment by brenoc** [comment]
@dfosco about a long list of categories, you could two things:

1. Give the list a max-height and overflow, so the user can scroll just the sublist
2. You could add a "Show all categories (120)", like OMS does:
![filters](https://cloud.githubusercontent.com/assets/284515/10149049/7f3df94e-660d-11e5-8bff-b18ce61c68ce.png)

**Comment by dfosco** [comment]
This small link on the bottom to *Show All* is a pretty good idea! We could add this as an optional setting on the editor.

This is the latest iteration for the category selection — showing two category levels. I'll work something close to OMS's for the filters :ok_hand: 

<img width="318" alt="screen shot 2015-09-28 at 6 21 59 pm" src="https://cloud.githubusercontent.com/assets/3229933/10149131/f5f3afe8-660d-11e5-9a90-479fdcf4d12a.png">
