### ISSUE TITLE
Replace SVGs in the theme with font-awesome

### ISSUE THREAD

**Issue by dfosco** [vtex-apps/storefront-theme#48]
@brenoc @tamorim @bellacorbo @bernardolemgruber As much as I want to use SVG, IE8 support is still a headache. Since we're already relying on Bootstrap, let's rely on font-awesome as well for our icons.

Any objections?

**Comment by tamorim** [comment]
The quality of the icons on mobile and, specially, iPhone is just as good or acceptable?

**Comment by dfosco** [comment]
Yes, it's acceptable.

Honestly, [SVGs are better at everything](https://css-tricks.com/icon-fonts-vs-svg/) and I'd rather use them, but:

 - Font-awesome is delivered via CDN, so there's a performance gain there
 - IE8 doesn't support SVGs :disappointed:

**Comment by brenoc** [comment]
Our [SVGIcon component](https://github.com/vtex-apps/storefront-theme/blob/master/src/utils/SVGIcon.js) has that in mind.

Ex:

```jsx
<SVGIcon svg={hamburgerIcon}
         fallback={hamburguerImg}
         width={18} height={18}
         fill="#153243"/>
```

**Comment by brenoc** [comment]
If the browser supports SVG, it renders the SVG, if not, it renders an image.

**Comment by brenoc** [comment]
@dfosco suggested to fallback to a font-awesome icon, that is good alternative too.

**Comment by brenoc** [comment]
Example:
```jsx
<SVGIcon svg={hamburgerIcon}
         fallback="fa-bars"
         width={18} height={18}
         fill="#153243"/>
```

**Comment by dfosco** [comment]
@brenoc @bernardolemgruber Maybe a fallback to font-aweome will be too troublesome, as we'll have to mimic our icons to match theirs.

Seeing that we'll be using our own SVGs (and they'll be probably made in Sketch), exporting them as `.pngs` will be a piece of cake :relieved:

**Comment by dfosco** [comment]
Given both choices using [SVGIcon component](https://github.com/vtex-apps/storefront-theme/blob/master/src/utils/SVGIcon.js), which one should we take?

 - Fallback `.svg` files with the same icons as `.png` or

 - Fallback `.svg` files with similar icons from *font-awesome* ?

**Comment by brenoc** [comment]
I think the first option is more flexible

2015-10-01 14:18 GMT-03:00 Daniel Fosco <notifications@github.com>:

> Given both choices using SVGIcon component
> <https://github.com/vtex-apps/storefront-theme/blob/master/src/utils/SVGIcon.js>,
> which one should we take?
>
>    -
>
>    Fallback .svg files with the same icons as .png or
>    -
>
>    Fallback .svg files with similar icons from *font-awesome* ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vtex-apps/storefront-theme/issues/48#issuecomment-144790984>
> .
>



-- 
*Breno Calazans*
Software Engineer
lab.vtex.com
+55 21 987872587

**Comment by dfosco** [comment]
I like this option better, but don't you think we'll lose some performance going with `.png`? Both because font icons are lighter and because we would be using Bootstrap's CDN.

**Comment by brenoc** [comment]
People that use older browsers are more patient hehe

2015-10-01 14:31 GMT-03:00 Daniel Fosco <notifications@github.com>:

> I like this option better, but don't you think we'll lose some performance
> going with .png? Both because font icons are lighter and because we would
> be using Bootstrap's CDN.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vtex-apps/storefront-theme/issues/48#issuecomment-144794692>
> .
>



-- 
*Breno Calazans*
Software Engineer
lab.vtex.com
+55 21 987872587

**Comment by dfosco** [comment]
Deal :smiley:
