### ISSUE TITLE
Production-ready Order Panel 

### ISSUE THREAD

**Issue by dfosco** [vtex-apps/storefront-theme#51]
![090cbf32-6c4b-11e5-8324-d21151b197f0](https://cloud.githubusercontent.com/assets/3229933/10321236/ffee3536-6c4d-11e5-8671-2bbb4fec49b7.png)

Prototype for Order Panel is done — in terms of styling and basic interaction. Functionality that still needs to be implemented:

1. `OrderOption` right now are just mocked divs in `OrderList`, but the files for the separated component are in place to do whatever's necessary to render the list properly. I'm not sure the component structure I have in place is ideal, so let's discuss this in person @tamorim.

2. Clicking an option should:

 - Change `data-is-selected` in the selected `OrderOption` to true 
 - Close `OrderPanel`
 - Reorder the list of products according to the selection
 - Save which `OrderOption` is true for the next interaction with `OrderPanel`

**Comment by dfosco** [comment]
By the way, this is currently in the branch `prototype/category-page` @ 985470a9687152cedb23818b210c4d1e65b7b6ff

**Comment by dfosco** [comment]
A small message for my friend @tamorim:

> When I give the devs detailed design specs but they don’t seem to be using them:
![tumblr_inline_nvm3dnbdvm1t9bsnt_500](https://cloud.githubusercontent.com/assets/3229933/10321348/8f2da164-6c4e-11e5-8dd4-322ee30e0c41.gif)

**Comment by brenoc** [comment]
@dfosco Why not change from "Ordernação" to "Ordernar por"

**Comment by dfosco** [comment]
@brenoc Good suggestion, it's better to have action-focused copy. Will do the same for the filters.

By the way, this was looking **AWFUL** :scream:. Please give me harsh feedback on the visual side of things when you think necessary. Made it a bit softer overall:

![ordernacao](https://cloud.githubusercontent.com/assets/3229933/10378255/4826d862-6dde-11e5-9fc0-eb5599c3a3be.png)
 softer now:

**Comment by brenoc** [comment]
@dfosco could the borders of the list be more thinner?

**Comment by dfosco** [comment]
@brenoc Still not sure of it — the larger borders help chunking the lists, which is specially important when you have multiples of them. 

Regardless, stores will change the styles to fit their needs, but I tend to verge on the side of visual hierarchy, even if it makes things less clean and... _Apple-like_ :iphone: :wink:

**Comment by tamorim** [comment]
I think this one is deprecated, we don't have a OrderPanel anymore.
This is done on FilterPanel, and it's working (needs change, but not on panel itself).
