### ISSUE TITLE
Correção no README

### ISSUE THREAD

**Issue by josantana** [vtex-apps/storefront-theme#70]
No tópico **3 - Iniciando o ambiente de desenvolvimento**, o comando citado não provoca o build, o upload dos arquivos, e não mostra a loja em desenvolvimento no lugar da Dreamstore.

Funciona com o comando abaixo:
```
vtex watch -w minhasandbox
```

**Comment by dfosco** [comment]
@tamorim Is this closed already or do you still have to merge it into `master`?

PS: @josantana we're trying to keep the issues as international as possible, that's why we're using english here :smile:

**Comment by tamorim** [comment]
Still have to merge it, waiting for someone to approve.
